version: "3"
services:
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    links:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./monitor/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    links:
      - nodejsserver
  nodejsserver:
    build: ./nodejsserver
    volumes:
      - ./nodejsserver:/app
    ports:
      - 8080:8080